# Generated by Django 5.2.2 on 2025-10-12 03:12

import django.db.models.deletion
import django.utils.timezone
import fotos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to=fotos.models.caminho_foto)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data_captura', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='obras.obras')),
            ],
            options={
                'ordering': ['data_captura', 'criada_em'],
            },
        ),
    ]
