# Generated by Django 5.2.2 on 2025-09-26 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('dia_inicia_relatorio', models.IntegerField()),
                ('dia_finaliza_relatorio', models.IntegerField()),
                ('empresa_responsavel', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario_criador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('clima_manha', models.CharField(max_length=20)),
                ('clima_tarde', models.CharField(max_length=20)),
                ('clima_noite', models.CharField(max_length=20)),
                ('clima_madrugada', models.CharField(max_length=20)),
                ('observacoes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario_criador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicosPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Efetivo_Direto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=40)),
                ('qtde', models.IntegerField()),
                ('presente', models.IntegerField()),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diarios.diarios')),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario_criador', models.CharField(max_length=100)),
                ('contrato_numero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diarios.contratos')),
            ],
        ),
        migrations.AddField(
            model_name='diarios',
            name='obra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diarios.obras'),
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('referencia', models.CharField(max_length=100)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diarios.diarios')),
                ('servicos_padrao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diarios.servicospadrao')),
            ],
        ),
    ]
