# Generated by Django 5.2.2 on 2025-10-08 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('clima_manha', models.CharField(max_length=20)),
                ('clima_tarde', models.CharField(max_length=20)),
                ('clima_noite', models.CharField(max_length=20)),
                ('clima_madrugada', models.CharField(max_length=20)),
                ('observacoes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario_criador', models.CharField(max_length=100)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='obras.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Efetivo_Direto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=40)),
                ('qtde', models.IntegerField()),
                ('presente', models.IntegerField()),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diarios.diarios')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('referencia', models.CharField(max_length=100)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diarios.diarios')),
                ('servicos_padrao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diarios.servicospadrao')),
            ],
        ),
    ]
