# Generated by Django 5.2.2 on 2025-10-12 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Efetivo_Direto_Padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=40)),
                ('qtde', models.PositiveIntegerField()),
                ('presente', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Efetivo_Indireto_Padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=40)),
                ('efetivo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='diarios',
            name='clima_manha',
            field=models.CharField(choices=[('limpo', 'Limpo'), ('nublado', 'Nublado'), ('chuva', 'Chuva'), ('impraticavel', 'Impraticável')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diarios',
            name='clima_noite',
            field=models.CharField(choices=[('limpo', 'Limpo'), ('nublado', 'Nublado'), ('chuva', 'Chuva'), ('impraticavel', 'Impraticável')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diarios',
            name='clima_tarde',
            field=models.CharField(choices=[('limpo', 'Limpo'), ('nublado', 'Nublado'), ('chuva', 'Chuva'), ('impraticavel', 'Impraticável')], max_length=20),
        ),
        migrations.CreateModel(
            name='Efetivo_Indireto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=40)),
                ('efetivo', models.IntegerField()),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diarios.diarios')),
            ],
        ),
    ]
