# Generated by Django 5.2.2 on 2025-09-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='empresa_responsavel',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='usuario_criador',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='obras',
            name='usuario_criador',
        ),
        migrations.AddField(
            model_name='obras',
            name='empresa_responsavel',
            field=models.CharField(default='Empresa', max_length=200),
            preserve_default=False,
        ),
    ]
