# Generated by Django 5.2.2 on 2025-09-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0002_remove_contratos_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico_Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('tipo_id', models.IntegerField()),
                ('descricao_alteracao', models.CharField(max_length=400)),
                ('usuario', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
