# Generated by Django 5.2.2 on 2025-10-19 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0002_efetivo_direto_padrao_efetivo_indireto_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarios',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diarios',
            name='data',
        ),
        migrations.RemoveField(
            model_name='diarios',
            name='usuario_criador',
        ),
        migrations.AddField(
            model_name='diarios',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diarios',
            name='clima_madrugada',
            field=models.CharField(choices=[('limpo', 'Limpo'), ('nublado', 'Nublado'), ('chuva', 'Chuva'), ('impraticavel', 'Impraticável')], max_length=20),
        ),
    ]
