# Generated by Django 5.2.2 on 2025-09-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0003_historico_edicao_alter_contratos_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diarios',
            old_name='obra_id',
            new_name='obra',
        ),
        migrations.RenameField(
            model_name='obras',
            old_name='contrato_numero',
            new_name='contrato',
        ),
        migrations.AlterField(
            model_name='contratos',
            name='numero',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
