# Generated by Django 5.2.2 on 2025-09-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarios', '0004_rename_obra_id_diarios_obra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='ativo',
        ),
        migrations.AddField(
            model_name='obras',
            name='situacao',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('parada', 'Parada')], default='andamento', max_length=20),
        ),
    ]
