# Generated by Django 5.2.2 on 2025-10-08 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('situacao', models.CharField(choices=[('andamento', 'Em andamento'), ('concluida', 'Concluída'), ('parada', 'Parada')], default='andamento', max_length=20)),
                ('empresa_responsavel', models.CharField(max_length=200)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contratos.contratos')),
            ],
        ),
    ]
