# Generated by Django 5.2.2 on 2025-10-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('cliente', models.CharField(max_length=200)),
                ('dia_inicia_relatorio', models.IntegerField()),
                ('dia_finaliza_relatorio', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
